# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e73c1b1c47238423a2fb623f89909e6421a506df708c3e2a6832fc4aac546187c328565abe409130f4ab91e77850b29540907bb235ce987f71fe1c9a3f99b02

test:
  secret_key_base: 066143cf2a64f4dd3087c54f6e617e8ddd962afb31f5233648bf9eda9c4b1cae4df3237d0e3dc6154364119d62b59c406c86b8073a6d46b8dbc778430dd7bb9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
